name: Merge to main

on:
  push:
    branches:
      - main

jobs:
  merge:
    name: Merge to main
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      # TODO Find a better version of anothrNick action that will actually detect
      - name: Bump version
        shell: bash
        run: |
          version=$(sed -nE 's/^const VERSION = "(.*)"/\1/p' cmd/execute.go)
          git tag $version
          git push origin $version
        

      - uses: cli/gh-extension-precompile@v2.0.0
        with:
          go_version: "1.23"